scrape_configs:
  - job_name: 'my-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['fall2020-comp598-1.cs.mcgill.ca:8082']
remote_write:
- url: https://prometheus-us-central1.grafana.net/api/prom/push
  basic_auth:
    username: 19229
    password: eyJrIjoiYmY5NzBhYjIwMjE3NzJmZDgyM2Y4NWJhYjFjYzg1ZjVhZjFkMmNjNCIsIm4iOiJwcm9tZXRoZXVzLW1ldHJpY3MiLCJpZCI6NDM1NzgyfQ==
