name: Inference-Test

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches:
      - main
      - dev
      - action

jobs:
  # Run inference test
  test-inference:
    name: Test inference
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup env 
      - name: setup env
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements.txt

      # Test the inference
      - name: Test inference
        run: 
          python model/inference/inference.py 6